name: Agent PR Launcher

on:
  issues:
    types: [opened, labeled]

permissions:
  issues:  write     # allow the job to add a comment
  contents: read     # checkout still needs this

jobs:
  launch:
    if: contains(github.event.issue.labels.*.name, 'reader')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ github.token }}   # default GITHUB_TOKEN
          script: |
            const issue = context.payload.issue;
            await github.issues.createComment({
              owner: context.repo.owner,
              repo:  context.repo.repo,
              issue_number: issue.number,
              body: '@codex-bot please begin implementing this reader per spec.'
            });
