name: Agent PR Launcher

on:
  issues:
    types: [opened, labeled]

permissions:
  contents: read
  issues:   write
  projects: write     # so the card moves when the comment is added

jobs:
  launch:
    if: contains(github.event.issue.labels.*.name, 'reader')
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: Experimental Lexer
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            const issue = context.payload.issue;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo:  context.repo.repo,
              issue_number: issue.number,
              body: '@codex-bot please begin implementing this reader per spec.'
            });
