# .github/workflows/auto-merge.yml
name: Auto-Merge Reader PRs
on:
  pull_request:
    types: [labeled, synchronize]

jobs:
  enable-automerge:
    if: |
      contains(github.event.pull_request.labels.*.name, 'reader') &&
      github.event.pull_request.mergeable_state == 'clean'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Enable Pull Request Automerge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
