# .github/workflows/auto-merge.yml
name: Auto-Merge Reader PRs

on:
  pull_request_target:
    types: [labeled, synchronize, opened]

permissions:
  contents: write    # needed to merge
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Automerge
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm install

      - name: Close completed TODOs
        run: node .github/scripts/close-todo.js
