# .github/workflows/auto-merge.yml
name: Auto-Merge Reader PRs
on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  enable-automerge:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/github-script@v6
        env:
          REQUIRE_APPROVAL: "true"
        with:
          github-token: ${{ secrets.AUTOMERGE_TOKEN }}
          script: |
            const pr = context.payload.workflow_run.pull_requests[0];
            if (!pr) {
              core.info('No pull request associated with this workflow run.');
              return;
            }
            const { data: prData } = await github.rest.pulls.get({
              owner: pr.base.repo.owner.login,
              repo: pr.base.repo.name,
              pull_number: pr.number,
            });

            const checks = await github.rest.checks.listForRef({
              owner: pr.base.repo.owner.login,
              repo: pr.base.repo.name,
              ref: pr.head.sha,
            });

            const allChecksPassed = checks.data.check_runs.every(run => run.conclusion === 'success');

            let approved = true;
            if (process.env.REQUIRE_APPROVAL === 'true') {
              const reviews = await github.rest.pulls.listReviews({
                owner: pr.base.repo.owner.login,
                repo: pr.base.repo.name,
                pull_number: pr.number,
              });
              approved = reviews.data.some(r => r.state === 'APPROVED');
            }

            if (
              prData.labels.some(l => l.name === 'reader') &&
              prData.mergeable_state === 'clean' &&
              allChecksPassed &&
              approved
            ) {
              await github.rest.pulls.merge({
                owner: pr.base.repo.owner.login,
                repo: pr.base.repo.name,
                pull_number: pr.number,
                merge_method: 'squash'
              });
            } else {
              core.info('PR not ready for auto-merge.');
            }
