# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  verify:
    name: Verify (OS: ${{ matrix.os }}, Node: ${{ matrix.node }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [18.x, 20.x]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Bootstrap project
        run: npm run setup

      - name: Lint & auto‐fix
        run: npm run lint

      - name: Run tests & collect coverage
        run: npm test

      - name: Build dist
        run: npm run build

      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-${{ matrix.os }}-node${{ matrix.node }}
          path: coverage/

  release:
    name: Release
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: verify
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Bootstrap project
        run: npm run setup

      - name: Build for release
        run: npm run build

      - name: Publish via Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release
