name: Spec-Code Drift Check
on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  drift:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: node .github/scripts/check-drift.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
