# .github/workflows/pr-context.yml

name: PR Spec Context
on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  issues: write
  contents: read

jobs:
  context:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: node .github/scripts/post-context.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
