name: Release

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  issues:   write
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm


      - name: Publish release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_WORKFLOW }}
          NPM_TOKEN:   ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
